# FILE: run_h2_lab.py
"""
Launcher for the Vulnerable HTTP/2 Lab environment.

This script configures and runs the `vulnerable_lab` application using the
Hypercorn ASGI server. It sets up an HTTPS server supporting HTTP/2 (ALPN 'h2')
to simulate a realistic environment for testing race conditions.

Dependencies:
    - hypercorn
    - tests.lab.vulnerable_lab (internal)
"""

from hypercorn.config import Config
from hypercorn.asyncio import serve
import asyncio
# It seems this file depends on tests being available.
try:
    from tests.lab.vulnerable_lab import app
except ImportError:
    # If tests are not in the path, this script won't run, but we can document it.
    app = None

# Configure Hypercorn
config = Config()
config.bind = ["127.0.0.1:5000"]
# We assume the CA cert/key are generated by scalpel_racer.py and present in the CWD.
config.certfile = "scalpel_ca.pem"
config.keyfile = "scalpel_ca.key"
config.alpn_protocols = ["h2"]

# [FIX] Allow 1000+ concurrent streams for stress testing
config.h2_max_concurrent_streams = 2000 

if __name__ == "__main__":
    print("[*] Running HTTP/2 Lab on https://127.0.0.1:5000")
    if app:
        asyncio.run(serve(app, config))
    else:
        print("[!] Error: Could not import 'vulnerable_lab'. Ensure 'tests/' is in your python path.")
